-- 建立文章表格
create table posts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  content text not null,
  user_email text not null
);

-- 開放權限 (Row Level Security) 讓大家能讀，登入者能寫
alter table posts enable row level security;
create policy "Public posts are viewable by everyone." on posts for select using ( true );
create policy "Users can insert their own posts." on posts for insert with check ( auth.role() = 'authenticated' );